# Analyzing bugs.python.org data

## Import statements and setup code

In [4]:
import pandas as pd
import numpy as np

In [5]:
from IPython.core.display import HTML
css = open('../style-table.css').read() + open('../style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

## Data import

In [7]:
issues = pd.read_csv('../data/2019-08-27-bpo.csv')

## Data inspection

Inspect the first few rows of data (head) and the last few rows of data (tail).

In [8]:
issues.head()

,title,id,stage,creation,creator,activity,actor,nosy,type,components,versions,dependencies,assignee,keywords,priority,status,resolution,nosy_count,message_count
0,ftplib Persistent data connection,2628,2,2008-04-13.23:50:10,6840,2010-08-07.16:33:11,155,"['252', '3080', '6840']",6,['9'],['16'],[],None,['2'],4,1,None,3.0,7.0
1,Improved doctest REPORT_*DIFFs with ELLIPSIS a...,9640,None,2010-08-19.11:04:09,10930,2010-08-19.11:06:03,10930,['10930'],6,['9'],['14'],[],None,['2'],4,1,None,1.0,2.0
2,Explain the default timeout in http-client-rel...,8595,None,2010-05-02.02:54:42,12311,2010-08-19.13:16:45,2799,"['1741', '2040', '2799', '12260', '12311', '12...",5,"['4', '9']","['1', '13', '14']",[],12260,[],4,1,None,6.0,7.0
3,Encodings and aliases do not match runtime,1249749,None,2005-08-01.18:23:30,2094,2010-08-21.18:46:24,12545,"['4', '8', '93', '2094', '12260']",6,['4'],['16'],[],12260,[],5,1,None,5.0,11.0
4,distutils extension library path bug on cygwin,1289136,3,2005-09-12.22:04:55,2347,2010-08-21.19:27:33,12545,"['35', '71', '2347', '4555']",5,['3'],"['13', '14', '16']",[],4555,[],4,1,None,4.0,6.0

In [9]:
issues.tail()

,title,id,stage,creation,creator,activity,actor,nosy,type,components,versions,dependencies,assignee,keywords,priority,status,resolution,nosy_count,message_count
7036,shutil.which wrong result on Windows,24505,None,2015-06-24.22:09:39,17566,2019-08-27.20:43:10,15487,"['301', '2377', '3951', '9663', '15467', '1548...",5,"['9', '15']",['20'],[],None,['2'],4,1,None,11.0,19.0
7037,shutil.which doesn't find files without PATHEX...,31405,None,2017-09-09.18:12:09,19707,2019-08-27.20:45:37,15487,"['301', '3951', '15467', '15487', '15623', '16...",5,"['9', '15']",['22'],[],None,[],4,1,None,9.0,8.0
7038,"shutil.make_archive (xxx, tar, root_dir) is ad...",35964,4,2019-02-11.12:40:46,30518,2019-08-27.20:46:19,15487,"['14', '1488', '1669', '4555', '13902', '15487...",None,['9'],"['14', '20', '21']",[],None,['2'],4,1,None,10.0,2.0
7039,CCompiler has_function displays warning,37965,None,2019-08-27.20:47:14,32216,2019-08-27.20:47:14,32216,"['7641', '17248', '32216']",5,['3'],"['19', '20', '21', '22', '23']",[],None,['2'],4,1,None,3.0,1.0
7040,Disallow fork in a subinterpreter broke subpro...,37951,4,2019-08-26.08:42:32,3108,2019-08-27.21:37:28,27838,"['252', '2377', '3108', '12704', '14000']",5,"['5', '8']","['22', '23']",[],14000,"['2', '21']",1,1,None,5.0,7.0

In [10]:
issues.count()

title            7041
id               7041
stage            7041
creation         7041
creator          7041
activity         7041
actor            7041
nosy             7041
type             7041
components       7041
versions         7041
dependencies     7041
assignee         7041
keywords         7041
priority         7041
status           7041
resolution       7041
nosy_count       7041
message_count    7041
dtype: int64

In [11]:
issues.shape

(7041, 19)

In [12]:
issues.dtypes

title             object
id                 int64
stage             object
creation          object
creator            int64
activity          object
actor              int64
nosy              object
type              object
components        object
versions          object
dependencies      object
assignee          object
keywords          object
priority          object
status             int64
resolution        object
nosy_count       float64
message_count     object
dtype: object

In [13]:
issues.describe(include=['object'])

,title,stage,creation,activity,nosy,type,components,versions,dependencies,assignee,keywords,priority,resolution,message_count
count,7041,7041,7041,7041,7041,7041,7041,7041,7041,7041,7041,7041,7041,7041
unique,7039,7,7041,7038,6641,8,225,124,259,105,38,7,13,71
top,Email parser creates a message object that can...,None,2011-08-07.08:33:00,2017-01-16.08:07:37,['155'],5,['9'],['22'],[],None,[],4,None,1.0
freq,2,3647,1,2,29,2798,1910,691,6773,4976,4040,6668,6943,1039

In [14]:
issues.describe(include=['int64'])

                 id       creator         actor  status
count  7.041000e+03   7041.000000   7041.000000  7041.0
mean   6.010933e+04  15275.218719  14217.386735     1.0
std    2.165050e+05   9852.099457   9889.237095     0.0
min    1.034000e+03      3.000000      1.000000     1.0
25%    1.845400e+04   5494.000000   4455.000000     1.0
50%    2.688200e+04  15623.000000  14674.000000     1.0
75%    3.364700e+04  23834.000000  22884.000000     1.0
max    1.778410e+06  32216.000000  32216.000000     1.0

In [15]:
# Get the column names
issues.columns

Index(['title', 'id', 'stage', 'creation', 'creator', 'activity', 'actor',
       'nosy', 'type', 'components', 'versions', 'dependencies', 'assignee',
       'keywords', 'priority', 'status', 'resolution', 'nosy_count',
       'message_count'],
      dtype='object')

In [16]:
# sort the dataframe by 'message_count'
issues.sort_values('message_count', ascending=False).head()

,title,id,stage,creation,creator,activity,actor,nosy,type,components,versions,dependencies,assignee,keywords,priority,status,resolution,nosy_count,message_count
6758,Clean up the documentation on module attributes,37800,None,2019-08-09.10:11:12,27679,2019-08-09.10:11:12,27679,"['12260', '14000', '27679']",6,['4'],['21'],[],12260,[],4,1,None,3.0,None
999,"PEP 3121, 384 Refactoring applied to ctypes mo...",15884,None,2012-09-08.17:59:36,1427,2014-06-29.23:20:54,1427,"['1076', '1427', '11255']",3,[],['19'],[],None,[],4,1,None,3.0,None
6398,mmap module add OpenBSD MADV_CONCEAL flag,37511,None,2019-07-05.20:51:43,27678,2019-07-05.20:51:43,27678,['27678'],None,[],['23'],[],None,[],4,1,None,1.0,None
3944,"Change description about doc in programming, faq.",33431,4,2018-05-05.10:06:00,28465,2018-05-05.10:13:53,28465,"['12260', '28465']",7,['4'],"['14', '18', '19', '20', '21', '22']",[],12260,['2'],4,1,None,2.0,None
4712,Parse trusted and signature information from X...,34950,None,2018-10-10.02:58:35,29672,2018-11-10.01:37:01,28506,"['3108', '28506', '29672']",None,['33'],['21'],[],3108,[],4,1,None,3.0,None

In [17]:
issues.groupby('stage').count()

,title,id,creation,creator,activity,actor,nosy,type,components,versions,dependencies,assignee,keywords,priority,status,resolution,nosy_count,message_count
stage,,,,,,,,,,,,,,,,,,
2,396,396,396,396,396,396,396,396,396,396,396,396,396,396,396,396,396,396
3,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057,1057
4,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852,1852
5,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
6,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63
7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
None,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647,3647

In [18]:
issues.groupby('components').count()

,title,id,stage,creation,creator,activity,actor,nosy,type,versions,dependencies,assignee,keywords,priority,status,resolution,nosy_count,message_count
components,,,,,,,,,,,,,,,,,,
"['1', '10', '22']",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"['1', '10']",7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
"['1', '12']",5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
"['1', '15', '30']",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"['1', '15']",25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"['9', '30']",5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
"['9', '32']",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
"['9', '33']",10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
['9'],1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910,1910
[],547,547,547,547,547,547,547,547,547,547,547,547,547,547,547,547,547,547

In [19]:
issues.groupby('activity').count()

,title,id,stage,creation,creator,actor,nosy,type,components,versions,dependencies,assignee,keywords,priority,status,resolution,nosy_count,message_count
activity,,,,,,,,,,,,,,,,,,
2010-08-07.16:33:11,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2010-08-19.11:06:03,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2010-08-19.13:16:45,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2010-08-21.18:46:24,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2010-08-21.19:27:33,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-08-27.20:43:10,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-08-27.20:45:37,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-08-27.20:46:19,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-08-27.20:47:14,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-08-27.21:37:28,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [20]:
issues.stage.value_counts()

None    3647
4       1852
3       1057
2        396
6         63
5         19
7          7
Name: stage, dtype: int64

In [21]:
issues['activity']

0       2010-08-07.16:33:11
1       2010-08-19.11:06:03
2       2010-08-19.13:16:45
3       2010-08-21.18:46:24
4       2010-08-21.19:27:33
               ...
7036    2019-08-27.20:43:10
7037    2019-08-27.20:45:37
7038    2019-08-27.20:46:19
7039    2019-08-27.20:47:14
7040    2019-08-27.21:37:28
Name: activity, Length: 7041, dtype: object

In [22]:
import datetime

In [23]:
test_date = issues['activity']

In [24]:
print(test_date)

0       2010-08-07.16:33:11
1       2010-08-19.11:06:03
2       2010-08-19.13:16:45
3       2010-08-21.18:46:24
4       2010-08-21.19:27:33
               ...
7036    2019-08-27.20:43:10
7037    2019-08-27.20:45:37
7038    2019-08-27.20:46:19
7039    2019-08-27.20:47:14
7040    2019-08-27.21:37:28
Name: activity, Length: 7041, dtype: object